#!/bin/bash
sm2 --start DATASTREAM AUTH OAUTH TIME_BASED_ONE_TIME_PASSWORD THIRD_PARTY_APPLICATION THIRD_PARTY_DELEGATED_AUTHORITY PUSH_PULL_NOTIFICATIONS_API

sm2 --start INTERNAL_LICENSING_MANAGEMENT_API_STUBS
./run_local.sh