openapi: "3.0.3"

info:
  version: 1.0.0
  title: Internal Licensing Management

servers:
  - url: https://test-api.service.hmrc.gov.uk/
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/
    description: Production

components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            write:internal-licensing-management: Write data for the internal licensing management
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: [ "application/vnd.hmrc.1.0+json" ]
      required: true

paths:
  /customs/licence/{licenceRef}:
    put:
      summary: Endpoint for upserting a licence
      description: |
        An endpoint that creates or updates a licence
      tags:
        - internal-licensing-management-api
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: './schemas/licence.json'
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "If the request is processed successfully and the licence is updated."
          content:
            application/json:
              schema:
                $ref: './schemas/response.json'
              example:
                {
                  "correlationId": "123e4567-e89b-12d3-a456-426655440000",
                  "sourceSystem": "CDS",
                  "destinationSystem": "ILBDOTI",
                  "licenceRef": "GBOIL123456",
                  "result": "ACCEPTED"
                }
        201:
          description: "If the request is processed successfully and the licence is created."
          content:
            application/json:
              schema:
                $ref: './schemas/response.json'
              example:
                {
                  "correlationId": "123e4567-e89b-12d3-a456-426655440000",
                  "sourceSystem": "CDS",
                  "destinationSystem": "ILBDOTI",
                  "licenceRef": "GBOIL123456",
                  "result": "ACCEPTED"
                }

      security:
        - userRestricted:
            - write:internal-licensing-management
